IVS.LeVanVen/Controllers/MeasureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using MODEL;
using PagedList;
using PagedList.Mvc;


namespace IVS.LeVanVen.Controllers
{
    public class MeasureController : Controller
    {
        public Measure_bll _measureBLL;
        public MeasureController()
        {
            _measureBLL = new Measure_bll();
        }

        [HttpGet]
        public ActionResult Index(Measure_model Model, int? page)
        {
            var pageNumber = page ?? 1;
            List<Measure_model> lstModel = new List<Measure_model>();
            int total = new int();
            if (!string.IsNullOrEmpty(Session["m_code"] as string))
            {
                Model.code = Session["m_code"].ToString();
            }
            if (!string.IsNullOrEmpty(Session["m_name"] as string))
            {
                Model.name = Session["m_name"].ToString();
            }
            _measureBLL.Search(Model, out lstModel, out total, pageNumber);
            var list = new StaticPagedList<Measure_model>(lstModel, pageNumber, 15, total);
            ViewBag.ListSearch = lstModel.OrderByDescending(x => x.id);
            ViewBag.page = 0;
            if (page != null)
            {
                ViewBag.page = pageNumber - 1;
            }
            return View(new Tuple<Measure_model, IPagedList<Measure_model>>(Model, list));
        }

        [HttpPost]
        [ActionName("Index")]
        public ActionResult IndexPost(Measure_model Model, int? page)
        {
            var pageNumber = page ?? 1;
            List<Measure_model> lstModel = new List<Measure_model>();
            int total = new int();
            _measureBLL.Search(Model, out lstModel, out total, pageNumber);
            var list = new StaticPagedList<Measure_model>(lstModel, pageNumber, 15, total);
            ViewBag.ListSearch = lstModel.OrderByDescending(x => x.id);
            Session["m_code"] = Model.code;
            Session["m_name"] = Model.name;
            TempData["CountResult"] = total.ToString() + " row(s) found!";
            return View(new Tuple<Measure_model, IPagedList<Measure_model>>(Model, list));
        }

        [HttpGet]
        public ActionResult Add()
        {
            Measure_model Model = new Measure_model();

            return View(Model);
        }

        [HttpPost]
        public ActionResult Add(Measure_model Model)
        {
            List<string> lstMsg = new List<string>();
            int returnCode = _measureBLL.Insert(Model, out lstMsg);
            if (ModelState.IsValid)
            {
                if (!((int)Common.ReturnCode.Succeed == returnCode))
                {
                    if (lstMsg != null)
                    {
                        for (int i = 0; i < lstMsg.Count(); i++)
                        {
                            ModelState.AddModelError(string.Empty, lstMsg[i]);
                        }
                    }
                    return View(Model);
                }
                TempData["Success"] = "Inserted Successfully!";
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public ActionResult View(int id)
        {
            if (string.IsNullOrEmpty(id.ToString()))
            {
                TempData["Error"] = "Data has already been deleted by other user!";
                return RedirectToAction("Index");
            }
            Measure_model Model = new Measure_model();
            int returnCode = _measureBLL.GetDetail(id, out Model);
            if (Model == null)
            {
                TempData["Error"] = "Data has already been deleted by other user!";
                return RedirectToAction("Index");
            }
            if (!((int)Common.ReturnCode.Succeed == returnCode))
            {
                Model = new Measure_model();
            }

            return View(Model);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            if (string.IsNullOrEmpty(id.ToString()))
            {
                TempData["Error"] = "Data has already been deleted by other user!";
                return RedirectToAction("Index");
            }

            Measure_model Model = new Measure_model();
            int returnCode = _measureBLL.GetDetail(id, out Model);
            if (Model == null)
            {
                TempData["Error"] = "Data has already been deleted by other user!";
                return RedirectToAction("Index");
            }
            if (!((int)Common.ReturnCode.Succeed == returnCode))
            {
                Model = new Measure_model();
            }

            return View(Model);
        }
        [HttpPost]
        public ActionResult Edit(Measure_model Model)
        {
            if (string.IsNullOrEmpty(Model.id.ToString()))
            {
                TempData["Error"] = "Data has already been deleted by other user!";
                return RedirectToAction("Index");
            }
            List<string> lstMsg = new List<string>();
            int returnCode = _measureBLL.Update(Model, out lstMsg);
            if (ModelState.IsValid)
            {
                if (!((int)Common.ReturnCode.Succeed == returnCode))
                {
                    if (lstMsg != null)
                    {
                        for (int i = 0; i < lstMsg.Count(); i++)
                        {
                            ModelState.AddModelError(string.Empty, lstMsg[i]);
                        }
                    }
                    return View(Model);
                }
                TempData["Success"] = "Updated Successfully!";
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Delete(List<int> id)
        {
            if (string.IsNullOrEmpty(id.ToString()))
            {
                TempData["Error"] = "Data has already been deleted by other user!";
                return RedirectToAction("Index");
            }
            List<string> lstMsg = new List<string>();

            int returnCode = _measureBLL.Delete(id, out lstMsg);
            if (((int)Common.ReturnCode.Succeed == returnCode))
            {
                return Json(new { Message = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { Message = false }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

IVS.LeVanVen/Views/Measure/Add.cshtml
@model MODEL.Measure_model

@{
    ViewBag.Title = "Add";
}
<div class="row" style="margin:30px 0 -20px 0">
    @Html.ActionLink("Home", "Index", "Measure", null, new { }) / @Html.ActionLink("Measure", "Index", "Measure", null, new { }) / Add
</div>
<hr />

@if (!String.IsNullOrEmpty((string)TempData["Error"]))
{
    <div id="error" class="error">
        @TempData["Error"]
    </div>
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    <div style="color:red;">* Indicates required fields</div>
    <table class="form-horizontal inputForm">
        <colgroup>
            <col class="col-md-1" />
            <col class="col-md-6" />
            <col />
        </colgroup>
        <tbody>
            <tr>
                <td class="pull-right">
                    @Html.DisplayNameFor(m => m.code)
                    <label class="lblRequirement">*</label>
                </td>
                <td>
                    @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control" } })
                </td>
            </tr>
            <tr>
                <td class="pull-right">
                    @Html.DisplayNameFor(m => m.name)
                    <label class="lblRequirement">*</label>
                </td>
                <td>
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                </td>
            </tr>
            <tr>
                <td class="pull-right">
                    @Html.DisplayNameFor(m => m.description)
                </td>
                <td>
                    @Html.TextAreaFor(m => m.description, new { @class = "form-control input-sm", maxlength = "256", @style = "height: 125px;" })
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    @Html.ActionLink("Back to List", "Index", "Measure", new { }, new { @class = "btn btn-sm btn-default" })
                    <input type="submit" value="Save" class="btn btn-sm btn-primary" />
                </td>
            </tr>
        </tbody>
    </table>

}


@section Scripts {
    <script>
        $(document).ready(function () {
            $('#code').focus();
        });
    </script>
}

IVS.LeVanVen/Views/Measure/Edit.cshtml
@model MODEL.Measure_model

@{
    ViewBag.Title = "Edit";
}
<div class="row" style="margin:30px 0 -20px 0">
    @Html.ActionLink("Home", "Index", "Measure", null, new { }) / @Html.ActionLink("Measure", "Index", "Measure", null, new { }) / Edit
</div>
<hr />

@if (!String.IsNullOrEmpty((string)TempData["Error"]))
{
    <div id="error" class="error">
        @TempData["Error"]
    </div>
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
    <div style="color:red;">* Indicates required fields</div>
    <table class="form-horizontal inputForm">
        <colgroup>
            <col class="col-md-1" />
            <col class="col-md-6" />
            <col />
        </colgroup>
        <tbody>
            <tr>
                <td class="pull-right">
                    @Html.DisplayNameFor(m => m.code)
                    <label class="lblRequirement">*</label>
                </td>
                <td>
                    @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control" } })
                </td>
            </tr>
            <tr>
                <td class="pull-right">
                    @Html.DisplayNameFor(m => m.name)
                    <label class="lblRequirement">*</label>
                </td>
                <td>
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                </td>
            </tr>
            <tr>
                <td class="pull-right">
                    @Html.DisplayNameFor(m => m.description)
                </td>
                <td>
                    @Html.TextAreaFor(m => m.description, new { @class = "form-control input-sm", maxlength = "256", @style = "height: 125px;" })
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    @Html.ActionLink("Back to List", "Index", "Measure", new { }, new { @class = "btn btn-sm btn-default" })
                    <input type="submit" value="Save" class="btn btn-sm btn-primary" />
                </td>
            </tr>
        </tbody>
    </table>

}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $('#code').focus();
        });


    </script>


}

IVS.LeVanVen/Views/Measure/Index.cshtml
@model Tuple<MODEL.Measure_model, IPagedList<MODEL.Measure_model>>
@using PagedList;
@using PagedList.Mvc;

@{
    ViewBag.Title = "Measure";
    int num = Convert.ToInt32(ViewBag.page) * 15;
}

<div class="row" style="margin:30px 0 -20px 0">
    @Html.ActionLink("Home", "Index", "Home", null, new { }) / Measure
</div>
<hr />
@if (!String.IsNullOrEmpty((string)TempData["Success"]))
{
    <div id="success" class="success">
        @TempData["Success"]
    </div>
}
@if (!String.IsNullOrEmpty((string)TempData["Error"]))
{
    <div id="error" class="error">
        @TempData["Error"]
    </div>
}
@if (!String.IsNullOrEmpty((string)TempData["CountResult"]))
{
    <div class="success">
        @TempData["CountResult"]
    </div>
}
<div style="margin:0px 0 -20px 0px">
    <div class="row">
        <div class="col-md-3" style="margin:0 -34px -20px 0">
            @Html.ActionLink("Add", "Add", "Measure", new { }, new { @class = "btn btn-primary btn-sm" })
            <button class="btn btn-danger btn-sm" id="Remove_items" url="@Url.Action("Delete", "Measure")">Delete</button>
        </div>
        @using (Html.BeginForm("Index", "Measure", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        { <form class="form-inline">
            <div class="form-group col col-md-3">
                @Html.TextBox("code", Model.Item1.code, new { @class = "form-control", @placeholder = "Code" })
            </div>
            <div class="form-group col col-md-3">
                @Html.TextBox("name", Model.Item1.name, new { @class = "form-control", @placeholder = "Name" })
            </div>
           
            <div class="form-group col col-md-3">
                <input class="btn btn-primary" value="Search" type="submit" />
            </div>
        </form>
        }
    </div>
</div>
<hr />
<div class="table-responsive" id="divLis">

    <table class="table table-bordered table-hover tableData">
        <tr class="headerTable" style="background-color: #337ab7; color: white;">
            <th  class="text-center"><input type="checkbox" name="checkAll" /></th>
            <th class="text-right">No</th>
            <th>
               Code
            </th>
            <th>
               Name
            </th>
            <th>
               Description
            </th>
        </tr>
        @if (ViewBag.ListSearch != null)
        {
            <tbody>
                @foreach (var item in Model.Item2)
                {
                    <tr>
                        <td class="text-center">
                            <input type="checkbox" name="check" value="@item.id" />
                        </td>
                        <td style="text-align:right">
                            @{ num++;}
                            <a href="@Url.Action("View", "Measure", new { @id = item.id }, null)">@num</a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.code)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.description)
                        </td>
                    </tr>
                }
            </tbody>
        }
    </table>
    @if (ViewBag.ListSearch != null)
    {
        @Html.PagedListPager((IPagedList)Model.Item2, page => Url.Action("Index", new { page }))
    }
</div>
@section Scripts {
    <script src="~/Scripts/bootbox.min.js"></script>
    <script>
        function Xoa(ID) {
            bootbox.confirm({
                size: "small",
                message: "Do you want to delete?",
                callback: function (result) {
                    if (result == true) {
                        tr = $(this).parents("tr");
                        $.ajax({
                            method: 'POST',
                            url: '/Measure/Delete',
                            data: { id: ID },
                            success: function (Success) {
                                if (Success.Message != null) {
                                    tr.hide(1000);
                                    bootbox.alert({
                                        message: "Delete successfully!",
                                        size: 'small'
                                    });
                                    location.reload();
                                }
                                else {
                                    bootbox.alert({
                                        message: "Unsuccessfully!",
                                        size: 'small'
                                    });
                                }

                            }
                        })
                    }
                }
            });
        };
    </script>
    <script>
        $(document).ready(function () {
            //remove click
            $(document).delegate("#Remove_items", "click", function (e) {
                e.preventDefault();

                var url = $(this).attr('url');
                var chk = document.getElementsByName("check");
                var data = [];
                for (var i = 0; i < chk.length; i++) {
                    if (chk[i].checked) {
                        data.push(chk[i].value);
                    }
                };
                if (data.length <= 0) {
                    bootbox.confirm({
                        size: "small",
                        message: "Please select items!",
                        callback: function (result) {
                            return true;
                        }
                    });
                }
                else {
                    bootbox.confirm({
                        size: "small",
                        message: "Do you want to delete?",
                        callback: function (result) {
                            if (result == true) {
                                $.ajax({
                                    url: url,
                                    type: "post",
                                    async: false,
                                    data: {
                                        "id": data
                                    },
                                    success: function (f) {
                                        location.reload();
                                    }
                                });
                            } else {
                                return true;
                            }
                        }
                    });
                }
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            $("input[name='checkAll']").click(function () {
                var checked = $("input[name='checkAll']").prop("checked");
                $("input[name='check']").prop("checked", checked);
            });
        });
    </script>
}

IVS.LeVanVen/Views/Measure/View.cshtml
@model MODEL.Measure_model

@{
    ViewBag.Title = "View";
}

<div class="row" style="margin:30px 0 -20px 0">
    @Html.ActionLink("Home", "Index", "Measure", null, new { }) / @Html.ActionLink("Measure", "Index", "Measure", null, new { }) / View
</div>
<hr />
@if (!String.IsNullOrEmpty((string)TempData["Success"]))
{
    <div id="success" class="success">
        @TempData["Success"]
    </div>
}
@if (!String.IsNullOrEmpty((string)TempData["Error"]))
{
    <div id="error" class="error">
        @TempData["Error"]
    </div>
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()
<table class="form-horizontal inputForm">
    <colgroup>
        <col class="col-md-1" />
        <col class="col-md-6" />
        <col />
    </colgroup>
    <tbody>
        <tr>
            <td class="pull-right">
                @Html.DisplayNameFor(m => m.code)
                <label class="lblRequirement">*</label>
            </td>
            <td>
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </td>
        </tr>
        <tr>
            <td class="pull-right">
                @Html.DisplayNameFor(m => m.name)
                <label class="lblRequirement">*</label>
            </td>
            <td>
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </td>
        </tr>
        <tr>
            <td class="pull-right">
                @Html.DisplayNameFor(m => m.description)
            </td>
            <td>
                @Html.TextAreaFor(m => m.description, new { @class = "form-control input-sm", maxlength = "256", @style = "height: 125px;", @readonly = "readonly" })
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                @Html.ActionLink("Back to List", "Index", "Measure", new { }, new { @class = "btn btn-sm btn-default" })
                @Html.ActionLink("Edit", "Edit", "Measure", new { @id = @Model.id }, new { @class = "btn btn-danger btn-sm" })
            </td>
        </tr>
    </tbody>
</table>
}